### ISSUE TITLE
Restore demo application

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#100]
Free Postgress database on Heroku has exceeded 10k row limit. Have cleared sessions and write permission should be restored soon.

**Comment by rev112** [comment]
I still cannot register, get "Server Error (500)" in return. Is it because of the same issue you've described?
Perhaps there are lots of bogus/spam registrations, and it makes sense to add a CAPTCHA?

**Comment by Bouke** [comment]
Heroku doesn't update the database stats; the free (dev) package is limited at 10k rows, while I've reduced the database to 3k rows. Once heroku updates the row count, everything should be restored. Not sure why it's taking 12+ hours though.

**Comment by Bouke** [comment]
After a few more hours, write access was restored.

**Comment by rev112** [comment]
Registration still doesn't work for me, it gives "Server Error (500)" after I click the "Register" button.

**Comment by Bouke** [comment]
Registration is now working again, however it now throws an error when trying to login.

**Comment by jake223** [comment]
When I register and log in it works, but when I try to set up two-factor it always tells me I have a bad token.

**Comment by Bouke** [comment]
@jake223 Are you using a token generator? The example config is set to 8 digits, maybe your app doesn't support that? I just verified that I can generate valid tokens on that site.

The login error is tracked in #102, so I'll close this issue.

**Comment by jake223** [comment]
My token generator was set to 6 digits. Thanks for the suggestion.
