### ISSUE TITLE
Make two factor authentication as one time authentication

### ISSUE THREAD

**Issue by parth7695** [Bouke/django-two-factor-auth#114]
I want to make two factor authentication as just one time mandatory thing, instead to current application made for every login. In short , i want to transfer the feature of two factor authentication which is currently bound to login to make it bounded to registration

**Comment by Bouke** [comment]
Seeing that you've also mailed me the same question, I'm not sure what you're asking:

* Make registering two-factor a mandatory step in the registration process, or/and,
* Don't validate the second factor when logging in.
