### ISSUE TITLE
login from mobile device using registered contact number and otp only (without password)

### ISSUE THREAD

**Issue by gladsonvm** [Bouke/django-two-factor-auth#116]
Hi,
I appreciate the effort you put into this. I would like to know if there is a feature that allows user to bypass password authentication with otp. Idea is to login with otp only if the user is signing in from a registered mobile device as the registered contact number will be auto populated.

**Comment by Bouke** [comment]
This is not a feature of this package. The reasoning is that the token is considered the second factor, the first factor being the password. Skipping the password would effectively mean that there's only a single factor.
