### ISSUE TITLE
Update django-otp to v0.3.1

### ISSUE THREAD

**Issue by bforchhammer** [Bouke/django-two-factor-auth#118]
`django-otp` added support for Django 1.8 in [v0.3.1](https://pythonhosted.org/django-otp/changes.html). Currently this version is not installed automatically because of the version constraint `'django_otp>=0.2.0,<0.2.99'` in `setup.py`.

Without the new version a clean database setup fails because the migration dependencies seem to not be setup correctly; specifically, the otp-migrations might get executed before the swappable user model is created.

**Comment by Bouke** [comment]
You didn't run into issues when using the 0.3.1 version? If so, the requirement can be loosened indeed.

**Comment by bforchhammer** [comment]
I haven't run into any issues so far. Seems to be working the same as before :)

**Comment by julianwachholz** [comment]
Version 0.3.1 is not quite compatible with 1.8+ yet. The commit that adds compatibility with the new app registry is here:

https://bitbucket.org/psagers/django-otp/commits/2dba952d7146aa8d05e2d1f85d3e25d353a9cdbf

This commit is not yet in any release.

**Comment by Bouke** [comment]
Seems to be working fine for the unit tests as well, updated in 9e0b037f5409f4638228112ba29378b469d630c6.
