### ISSUE TITLE
Deprecated warning in django 1.8

### ISSUE THREAD

**Issue by TheRakken** [Bouke/django-two-factor-auth#124]
/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

**Comment by Tusky** [comment]
That has nothing to do with TFA. Seems like you don't have `django.contrib.sites` in your installed apps. Which is a Django default, and TFA do uses it, even if you have only 1 site.

**Comment by TheRakken** [comment]
Thanks.
