### ISSUE TITLE
Current release is incompatible with Django >= 1.7; fixed in master

### ISSUE THREAD

**Issue by aaugustin** [Bouke/django-two-factor-auth#128]
django-otp only gained native Django migrations in version 0.3.0. The tag for 0.3.0 directly follows the commit that added native Django migrations to all apps.

https://bitbucket.org/psagers/django-otp/commits/01fe986b9fc23b136e92c798502c763e7e3a835d
https://bitbucket.org/psagers/django-otp/commits/cf6cd0b34451bfcd64956b008cca8d412e9d2c06

The current release of django-two-factor-auth is 1.2.1. It depends on django-otp>=0.2.0,<0.2.99. So `pip install django-two-factor-auth` installs `django-otp==0.2.7`. This makes it impossible to use Django >= 1.7 because the `'otp_static.StaticDevice'` model has a foreign key to the `AUTH_USER_MODEL` and no native Django migrations.

Indeed, Django doesn't allow models without migrations to depend on models with migrations, because the backwards compatibility layer starts by creating all models without migrations and then migrates those with migrations.

In practice we get the following error when trying to run our tests:

    ALTER TABLE "otp_static_staticdevice" ADD CONSTRAINT "otp_static_staticdevi_user_id_107aea364f0973a5_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED

    psycopg2.ProgrammingError: relation "users_user" does not exist

(We have `AUTH_USER_MODEL = "users.User"`.)

This was fixed in master six weeks ago. It would be very helpful if you could push a release to PyPI. (We manage our dependencies with pip-tools, which makes it inconvenient to pin git commits of libraries which have dependencies.)

**Comment by Bouke** [comment]
Thanks for the report. Sadly some changes in Django are preventing releasing from master, as demonstrated by the failing tests. I've released a patch (1.2.2) in the interim.

**Comment by aaugustin** [comment]
Thank you very much!
