### ISSUE TITLE
Django 1.9 compatibility?

### ISSUE THREAD

**Issue by VincentVW** [Bouke/django-two-factor-auth#132]
Is django-two-factor-auth Django 1.9 compatible yet? 

I saw you made some changes to support 1.9, is this still a work in progress? Today we wanted to upgrade our project to 1.9 and while upgrading packages, Django 2F auth reverted this to 1.8.x. When using the GitHub version instead of the pypi release all went fine.

**Comment by Bouke** [comment]
The next release will be a new minor version, so I want to get as much of the pending work in as possible. For now only #113 is pending a merge, but I don't have the time at the moment to complete that. So any help would be appreciated.

**Comment by Bouke** [comment]
Version 1.3.0 was released two months ago including support for Django 1.9.

**Comment by Benjamin-Kozuch** [comment]
Is Django 1.9 still supported and if so, how much longer will it be supported?

**Comment by moggers87** [comment]
1.5.0 was the last version to support Django 1.9.

**Comment by Benjamin-Kozuch** [comment]
Thanks for answering so quick! So if we use version 1.5.0 things should go smooth with Django 1.9?

**Comment by moggers87** [comment]
Maybe? This package has other dependencies (like django_otp) which you will need to pin on older versions too.

**Comment by Benjamin-Kozuch** [comment]
Gotcha thanks!
