### ISSUE TITLE
Configuring TWO_FACTOR_SMS_GATEWAY in settings.py

### ISSUE THREAD

**Issue by epalm** [Bouke/django-two-factor-auth#133]
I'm following http://django-two-factor-auth.readthedocs.org/en/1.2.2/configuration.html#general-settings and I want to set a fake sms gateway.

When I add
> import two_factor
> TWO_FACTOR_SMS_GATEWAY = two_factor.gateways.fake.Fake

I get

> AttributeError: 'module' object has no attribute 'fake'

Pardon my ignorance, where is this setting supposed to go?

**Comment by Bouke** [comment]
The documentation should list quotes there, so:

    TWO_FACTOR_SMS_GATEWAY = "two_factor.gateways.fake.Fake"
