### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by aaugustin** [Bouke/django-two-factor-auth#137]
This commit changed a model field:
https://github.com/Bouke/django-two-factor-auth/commit/0ba9fea143d04152f5837384a93a02257ea3c682#diff-2afce380c543f1ec32ec166198de5498L13

As a consequence, it needs a migration.

Before this commit, the max length for phone numbers was 16. After this commit, it's 128 (the default of django-phonenumber-field). As a consequence, numbers with a length between 17 and 128 inclusive pass Django's validation but are rejected by the database.

I noticed this issue while making consistency checks on a database schema. I haven't encountered it in practice because people don't tend to enter numbers with more than 16 digits.

Even if you set the length limit back to 16 digits, you should still make a migration for Django to record the change.

**Comment by seanbell** [comment]
:+1:

**Comment by Bouke** [comment]
Fixed in 54fb93e6cca76c959bf160ab181fd21271ca8dee. Thanks for the bug report. We're sticking to PhoneNumber field's default length of 128 characters, although 16 should suffice for most of us.
