### ISSUE TITLE
Turn On/Off configuration

### ISSUE THREAD

**Issue by imaia** [Bouke/django-two-factor-auth#140]
During local development, it would be nice to be able to turn on and off OTP easily.

**Comment by Bouke** [comment]
At the moment no such feature is planned. I'm also not quite sure if it's the correct approach, my development environment should reflect what's going to be in production, so having different security mechanisms per environment doesn't contribute to that.

**Comment by imaia** [comment]
Actually, my environment requires two factor authentication for everything and, I'm not sure how I should use two factor authentication while writing tests for my application. I'm actually turning off the "is_verified" method.
