### ISSUE TITLE
Question: django-user-sessions versus django.contrib.sessions

### ISSUE THREAD

**Issue by thebigspoon** [Bouke/django-two-factor-auth#141]
Your documentation seems to recommend the `django-user-sessions` package over `django.contrib.sessions` because it "improves account security control".

Is there anyway you can elaborate on where these security vulnerabilities exist if using `django.contrib.sessions` to manage sessions?

The biggest advantage of `django-user-sessions` seems to be that we can query sessions as we would other models.

Thanks

**Comment by Bouke** [comment]
I think you intended to post this under [Bouke/django-user-sessions][1].

> Is there anyway you can elaborate on where these security vulnerabilities exist if using django.contrib.sessions to manage sessions?

There's no mentioning of security vulnerabilities. The package's goal is to  "improve account security **control**". For example listing a user's active sessions and selectively terminate those sessions.

> The biggest advantage of django-user-sessions seems to be that we can query sessions as we would other models.

Correct.

[1]: https://github.com/Bouke/django-user-sessions
