### ISSUE TITLE
What needs to happen for this to be recommended for production use?

### ISSUE THREAD

**Issue by timabbott** [Bouke/django-two-factor-auth#156]
Since this package seems to be the most complete Django project doing 2FA, and I don't think every Django project should write its own 2FA support, I'd like to use this in Zulip (https://github.com/zulip/zulip/).

It's hard to miss the warnings on GitHub and pypi that this package is unmaintained and not recommended for production use.  But I've noticed that code has been merged over the last few months; is the package maintained again now?  

If not, what would it take to make this package ready for production use?  Are there known significant bugs that need to be resolved, should we be trying to recruit someone to help out with maintaning this at DjangoCon next week, or something else?

**Comment by MarkusH** [comment]
I'm currently looking into the project state and talked to @Bouke about maintenance.

**Comment by timabbott** [comment]
Cool!  Would be super awesome to see this have a maintainer.

**Comment by MarkusH** [comment]
@timabbott you mentioned DjangoCon US above. I'm there as well. Find me please and let us talk about this project :)

**Comment by timabbott** [comment]
I won't be there but @rishig on the Zulip team will be there for both days of the sprints.

**Comment by rishig** [comment]
Yup! Will be there Thursday and Friday, look forward to meeting you :).
