### ISSUE TITLE
Q: Migrate with another system

### ISSUE THREAD

**Issue by N3TC4T** [Bouke/django-two-factor-auth#170]
Hey

first I should say thanks for this awesome module .
and here is my question : in other systems verification is by users emails and generating a link for verifying user but in our system we verify users by their mobile phone and saving there mobile phone in a table with number , key (that sent to them) , verifyed and user object , now I wanna when user try to active two factor system , they choose their number (that verifyed before) from my table .
should I make another record in phone_devices model for activing two factor for them ?
what is your suggestion ?

**Comment by MarkusH** [comment]
If you want to use 2FA via SMS you can use the twilio backend to do that.

**Comment by Bouke** [comment]
If you want to switch all your users to TFA, you could add their phone numbers to the table `two_factor_phonedevice`. Beware that you'd need to generate a unique `key` for all those entries -- never share a key between multiple entries. Use `django_otp.util.random_hex` to generate those keys.
