### ISSUE TITLE
500 Server Error on Demo App

### ISSUE THREAD

**Issue by jcquinlan** [Bouke/django-two-factor-auth#171]
I'm getting a 500 Internal Server Error on the login page, and after attempting to create an account within the demo application hosted via Heroku.

**Comment by Bouke** [comment]
Ah yes, that issue again. We're on a free tier of the database, which has exceeded the max of 10k rows. The database needs some pruning before it will accept new rows (e.g. registrations / sessions). We should have some auto cleanup in place, so the database will remain within its limits.

**Comment by jcquinlan** [comment]
Coolio, any idea of the timeframe on that cleanup?

**Comment by Bouke** [comment]
I've emptied the database. I was in the process of automating this, but apparently my buildpack on heroku is outdated and all dependencies have aged. So the change cannot be pushed at the moment, but at least the site is working again.
