### ISSUE TITLE
Works with Django Social Auth?

### ISSUE THREAD

**Issue by JakeAustwick** [Bouke/django-two-factor-auth#172]
Hi,

Before integrating this package I just wanted to check whether the two-factor authentication would work in combination with Django Social Auth?

https://github.com/omab/django-social-auth

**Comment by MarkusH** [comment]
I haven't checked it, but the essential thing is that after the `LoginView` you redirect your user to the `SetupView` which handles all 2 factor settings. So, generally, I'd say there should be a fairly easy way to get this working.

**Comment by audiolion** [comment]
an interesting example would be integrating with social auth, including a booleanfield in the user model or foreign key profile model of whether the user wants to enable 2FA and determine routing based on that

**Comment by Bouke** [comment]
The aim of this package is to provide an easy user interface on top of `django_otp`. At the moment this means that there is a hard coupling between the first factor (credentials) and the second factor (OTP).

Using django-social-auth you'd typically want to skip the first factor (credentials), as you've "outsourced" that to the social network provider. You could implement your own token input form, or use `django_otp` directly instead.

**Comment by PetrDlouhy** [comment]
I was able to fix the problem by using `django_otp.login()` in the view:

```python
from django.views.generic import FormView
from social_django.utils import load_strategy
from two_factor.forms import AuthenticationTokenForm
from two_factor.utils import default_device
import django_otp


class AuthenticationView(FormView):
    template_name = "two_factor/core/login.html"
    form_class = AuthenticationTokenForm

    def get_success_url(self):
        partial = self.get_partial()
        self.request.session["tfa_completed"] = True
        self.request.user = self.get_partial().kwargs["user"]
        django_otp.login(self.request, self.device)
        return (
            reverse("social:complete", kwargs={"backend": partial.backend})
            + f"?partial_token={partial.token}"
        )

    def get_partial(self):
        strategy = load_strategy()
        partial_token = self.request.GET.get("partial_token")
        partial = strategy.partial_load(partial_token)
        return partial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        user = self.get_partial().kwargs["user"]
        kwargs["user"] = user
        kwargs["initial_device"] = default_device(user)
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["wizard"] = {"steps": {"current": "token"}}
        return context
```

So now it seems to be working.
I would be glad, if some of this code could become part of `django-two-factor-auth` or at least it is mentioned in the documentation for new users how to use it with Django social auth.

**Comment by moggers87** [comment]
Wouldn't it be easier to implement your own decorator that checks to see if the user is *either* logged in via social auth *or* has logged in with 2fa?

I think you'd be hard pressed to convince me to merge any code specifically for social auth - it's not the only social auth django app out there and the project appears to be a bit in flux (there are multiple "deprecated" repoes, no links to docs, etc.)

**Comment by PetrDlouhy** [comment]
> Wouldn't it be easier to implement your own decorator that checks to see if the user is either logged in via social auth or has logged in with 2fa?

I am not sure which decorator do you have in mind, but anyway I wanted to achieve that the 2FA will be enforced after social authentication, because that alone might not be secure enough.

> I think you'd be hard pressed to convince me to merge any code specifically for social auth - it's not the only social auth django app out there and the project appears to be a bit in flux (there are multiple "deprecated" repoes, no links to docs, etc.)

OK, I will make the code into separate application and still would appreciate if it could be linked from the docs here.

**Comment by PetrDlouhy** [comment]
@moggers87 I made [dj-2fa-social-auth](https://github.com/PetrDlouhy/dj-2fa-social-auth) app to connect these two apps. PyPI package is https://pypi.org/project/dj-2fa-social-auth/

Could you please add it to docs, so others will find it?
