### ISSUE TITLE
Password protected pages

### ISSUE THREAD

**Issue by guillaumepiot** [Bouke/django-two-factor-auth#173]
Hello,

I have recently integrated this package into our current Django auth workflow without any issues. I believe that we could increase security by adding password protected pages for:
- Show Backup Tokens (`/two_factor/backup/tokens/`)
- Disable Two-factor Authentication (`/two_factor/disable/`)

The idea is that someone could access a logged in user computer maliciously and grab its token or even disable the two step auth on their behalf. A good way of preventing this security weakness would be to ask the user to re-enter their login password to see the backup token and disable two-factor auth.

Those pages would present a password form and on POST success display the backup tokens or disable the two-factor auth.

I wonder if you guys think it's worth implementing, or if you could point me to the best approach of doing so in a fork.

**Comment by moggers87** [comment]
I use [django-sudo](https://github.com/mattrobenolt/django-sudo) for exactly this.

**Comment by guillaumepiot** [comment]
@moggers87 thanks for the tip. Although I have implemented it manually now, I certainly consider it on the next project.
