### ISSUE TITLE
Cannot reach backup codes screen without putting in a dummy token

### ISSUE THREAD

**Issue by jaylett** [Bouke/django-two-factor-auth#177]
Django will generate a required `IntegerField` with a `required` attribute (and min/max validators):

``` html
<input id="id_token-otp_token" max="999999" min="1" name="token-otp_token" required="" type="number">
```

This means in some recent browsers (certainly Firefox, here) you can't submit the token form using the "Use backup token" button, because you get a validation error on the token input field. This needs to be an optional field, or you have to put a valid but dummy token in (eg 1), which isn't particularly guessable for most people. That will then require some more subtle validation of the `Form` on the backend (and possibly some dynamic rather than declarative validation on the front end).

**Comment by Bouke** [comment]
The "real" issue here is that the backup tokens should also do a POST and in HTML5 it isn't allowed to nest ``<form>``s. So to have the "use backup token" button shown inside the form, some server-side pre-form POST handling is required to redirect the user to another screen.

Another easy solution would be to disable client-side validation of the form field by adding a ``novalidate`` attribute. This way we'd still be able to use Django's form validation and render "use backup token" inside a single ``<form>``.

**Comment by jaylett** [comment]
I have a couple of questions here:

1. Is there a security reason to have a separate backup code section? You could put the backup token in as a regular token and, since it's a different format, detect on the backend what's going on. (Number input fields aren't terribly useful on desktop for this anyway, since the bumpers are kind of pointless for a token — although [you can style them out on webkit](https://css-tricks.com/snippets/css/turn-off-number-input-spinners/) and there are presumably similar approaches for other browsers).

2. If you need the UX to be that way for security reasons, could you have two `<form>`s on the page, and put the management form from the wizard in both? Then you get just the pertinent information submitted.

Adding `novalidate` sounds like a reasonable short-term solution until a more complete approach can be taken.

**Comment by Bouke** [comment]
I've disabled the `required` attribute for now. Can you confirm that this works for you as well?

Regarding your questions:

1. The generated backup tokens are alphanumeric, so they wouldn't match the input expected by `NumberField`. The main reason to keep using `NumberField` is so mobile users are shown the correct on-screen keyboard by default.

2. That's a great idea. I think the current layout was adopted to provide a similar user experience to Google's. When this package was created two factor authentication wasn't as wide-spread as it is now. We could probably introduce a new UX without scaring users.

**Comment by jaylett** [comment]
@Bouke seems to work here, thanks!
