### ISSUE TITLE
Google Authenticator does not work with example app - 2016

### ISSUE THREAD

**Issue by sdann** [Bouke/django-two-factor-auth#184]
Ref #38:

I'm having this same problem now with the example application.

Username: firewill
Password: tatortot

After scanning the 2D barcode into Google Authenticator and entering the first token, the token is not accepted with an error of:

"Entered token is not valid."

I'm using an HTC 10, but my time is correct on the phone, and my Google Authenticator app works for multiple other TOTP based 2FA sites.

**Comment by Bouke** [comment]
> Congratulations, you've successfully enabled two-factor authentication.
Using Google Authenticator on iPhone. I'm not quite sure why the token is rejected. The token is set to a length of 8 digits. Could that be related?

**Comment by MarkusH** [comment]
Yes, that sounds like a probable cause. Google Authenticator can only deal with 6 digit codes.

**Comment by sdann** [comment]
Yes, that's most likely it.  The OSS version of Google Authenticator is a fork of the Play Store app, but it can't do 8 digit codes and has an issue tracking the feature request.

https://github.com/google/google-authenticator-libpam/issues/20

I can find no way in the Android Google Authenticator app to display 8 digit codes.

**Comment by Bouke** [comment]
I found the issue. I tried reverting to 6 digits a while back, but Heroku deprecated some parts of the infra that the example app used. That required me to make some changes, which I didn't have time for. I've now successfully deployed a completely updated example app and should work with 6 digits now. Most likely any paired token generators will fail, as they will continue to generate 8 digit tokens.

**Comment by sdann** [comment]
Thanks @Bouke.  I've also confirmed I'm now able to log in to the example app with my Android Google Authenticator app and 6 digit codes.
