### ISSUE TITLE
Please release v1.5!

### ISSUE THREAD

**Issue by grahamu** [Bouke/django-two-factor-auth#185]
Hi maintainers. Your current documentation says DTFA supports Django v1.10. This is true for "master" branch as a result of [this commit](https://github.com/Bouke/django-two-factor-auth/commit/8e47e884918b169bdfd42af60d672ea2a1e5cc20). However, you haven't released a new version to PyPi since this update. Developers using PyPi to install requirements are stuck using Django v1.9 or lower. Seems like true support for Django v1.10 would be a very good reason to release a new version to PyPi.

Thanks!

**Comment by Bouke** [comment]
Done!

**Comment by grahamu** [comment]
Superb, thanks very much Bouke!
