### ISSUE TITLE
In demo, token generator doesn't work with Google Authenticator

### ISSUE THREAD

**Issue by prateekporwal** [Bouke/django-two-factor-auth#189]
I signed up to see the demo here http://example-two-factor-auth.herokuapp.com/

When I try to enable Two factor authentication using Token Generator method, which gives a QR code, the token generated by Google Authenticator doesn't match and throws `Entered token is not valid.` Attaching screenshot to make it easier to debug.

![image](https://cloud.githubusercontent.com/assets/16544274/22022128/a138fd18-dce6-11e6-981a-1a2e9c596850.png)

**Comment by Bouke** [comment]
I just verified with Google Authenticator on iOS and the demo is working fine for me.

On which platform does this happen, Android / iOS? What is the version of the app? Have you verified that the date and time on your device are setup correctly?

**Comment by prateekporwal** [comment]
I tried again now. It worked this time. Haven't changed anything in my date time setting. Wondering what would have caused this. 

Anyways. Thanks. I will close this.
