### ISSUE TITLE
Version of django-phonenumber-field

### ISSUE THREAD

**Issue by suriya** [Bouke/django-two-factor-auth#190]
I see that `django-two-factor-auth` requires `django-phonenumber-field>=0.7.2,<0.99`. https://github.com/Bouke/django-two-factor-auth/blob/d6d9149410ef0850a320ce78e84d2a07c71d0a37/setup.py#L19

Is there any reason why a later version of `django-phonenumber-field` is not acceptable? I use version 1.1.0 (at present, the latest version) of `django-phonenumber-field` and `django-two-factor-auth` conflicts with my existing setup.

**Comment by suriya** [comment]
I don't know of a good way to definitively answering this question. After examining the respective releases 0.7.2 and 1.1.0, it seems that django-phonenumber-field moved from using phonenumberslite instead of phonenumbers as a dependency (this is a backward compatible change).

**Comment by Bouke** [comment]
I've updated the dependency. It will be incorporated in a future release.
