### ISSUE TITLE
Rejects phone numbers that starts with 00 instead of +

### ISSUE THREAD

**Issue by lcamacho** [Bouke/django-two-factor-auth#191]
Hi, I've been trying to input several numbers with 00 as prefix but none of them are accepted.

**Comment by Bouke** [comment]
Can you test whether this also happens on http://example-two-factor-auth.herokuapp.com? Can you provide your test data? What versions of the dependencies are you using (`pip freeze`)? I cannot replicate with `"003612345678"`, which works fine.

**Comment by Bouke** [comment]
Closing issue due to lack of information.
