### ISSUE TITLE
Incorrect gateway used?

### ISSUE THREAD

**Issue by vikram-lapenatech** [Bouke/django-two-factor-auth#196]
Even if i am giving valid twilio credentials , the message "your token is 1234 " is diplaying.

```
TWO_FACTOR_CALL_GATEWAY = 'two_factor.gateways.twilio.gateway.Twilio'
TWO_FACTOR_SMS_GATEWAY 	= 'two_factor.gateways.twilio.gateway.Twilio'
TWILIO_ACCOUNT_SID 		= 'AC86a1663acf************affba5d3'
TWILIO_AUTH_TOKEN 		= '029be37d7**********1c0257c9b'
TWILIO_CALLER_ID 		        = '+919781539134'                #verified caller ID
```

**Comment by Bouke** [comment]
It appears as if you're using the example project, as it would be the only explanation for [that message](https://github.com/Bouke/django-two-factor-auth/blob/master/example/gateways.py#L12) appearing on your screen. Please follow the installation/configuration instructions, somewhere it tells you to set the correct `TWO_FACTOR_CALL_GATEWAY` and `TWO_FACTOR_SMS_GATEWAY`.
