### ISSUE TITLE
Customize redirect on phone number delete

### ISSUE THREAD

**Issue by italomaia** [Bouke/django-two-factor-auth#197]
It would be nice to be able to configure the success_url on phone delete. Right now, it redirects to the LOGIN_URL, which is not necesserally the desired behavior.

**Comment by Bouke** [comment]
You can already do this, by overriding `success_url` in the routes. You'd have to include all the routes manually instead of using `include()` however.

**Comment by italomaia** [comment]
So, no settings for this? No "next" param on the url? Seems like a common use case.
