### ISSUE TITLE
Make coveralls only comment once on a PR

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#201]
Currently 'coveralls' submits ~10 coverage reports per PR. This is highly annoying. It doesn't appear to be resolved anytime soon either: https://github.com/lemurheavy/coveralls-public/issues/491. So we'll have to fix this downstream.

**Comment by moggers87** [comment]
You could move to codecov, they have a way of controlling how PRs are commented on: https://docs.codecov.io/docs/pull-request-comments

**Comment by Bouke** [comment]
Codecov only submits one comment, and updates it if necessary on follow-ups. Looks good!
