### ISSUE TITLE
Release new version to PyPi

### ISSUE THREAD

**Issue by pypetey** [Bouke/django-two-factor-auth#202]
Django 1.11 has been released. 

It would be great if recent version of django-two-factor-auth would be released on PyPi

**Comment by Bouke** [comment]
Support for Django 1.11 is not yet complete. See also: https://travis-ci.org/Bouke/django-two-factor-auth/jobs/218811641.

**Comment by Bouke** [comment]
Ah it seems the tests on travis/tox have not been setup correctly.

**Comment by Bouke** [comment]
I've resolved the test failures, but cannot upload the distribution because of missing trove classifiers on pypi: https://github.com/pypa/pypi-legacy/issues/624.

**Comment by jamescooke** [comment]
Classifiers are up now :smile: https://github.com/pypa/pypi-legacy/issues/624

**Comment by Bouke** [comment]
New version's uploaded!
