### ISSUE TITLE
Support for Twilio 6.0 library

### ISSUE THREAD

**Issue by ipartola** [Bouke/django-two-factor-auth#203]
The 5.7 version of the official Twilio library will lose support in July 2017 (see https://www.twilio.com/docs/libraries/python/migration-guide). It seems the changes required would be minimal. Is it possible to transparently add support for both versions?

**Comment by Bouke** [comment]
Sure, although dropping support for 5.7 would be fine by me as well. Any chance you could work on a PR for this?

**Comment by ribalba** [comment]
PR is here: https://github.com/Bouke/django-two-factor-auth/pull/206

**Comment by wesvetter** [comment]
@Bouke Can you cut a new release for this?

**Comment by Bouke** [comment]
I've just released 1.6.1 with this fix! :shipit:
