### ISSUE TITLE
feature suggestion:  allow "once-only" display of backup tokens once setup is complete

### ISSUE THREAD

**Issue by hjwp** [Bouke/django-two-factor-auth#217]
this is a security enhancement proposal I guess?

we were thinking of adding an extra layer of security to our site by, for example, requiring a token if the user wishes to change their password, disable tfa, or perform other sensitive account operations.  this means that, even if a user has their session hijacked somehow, or perhaps leaves their computer unguarded, an attacker cannot do too much damage.

but then we realised that the attacker can just go to the "view my backup tokens" page (from `two_factor.views.BackupTokensView`) and use one of the backup tokens.

we could disable that view, but that same information is still available via the "success_url" of `two_factor.views.SetupView` -- we do have to display the backup tokens to the user at least once, and if we do so from a page with a normal GET request, then it has a URL, and it can be viewed again.

so the feature request is:  some way of being able to display backup tokens "once-only", such that they can't ever be seen again.  options:

- use django messages framework at the end of a successful trip through `SetupView`
- render a one-off template after processing the final `SetupView` POST instead of redirecting to a sucess_url

I think we might have a go at the first of those two options.   Do let me know if I'm making some obvious mistake or I have misunderstood something here?

**Comment by moggers87** [comment]
Have you looked at [django-sudo](https://github.com/mattrobenolt/django-sudo)? It asks for the user's password before allowing them to access a decorated view (like Github does with certain pages). This also avoids having to worry about backup tokens - just protect all your 2fa views with django-sudo.

**Comment by hjwp** [comment]
thanks for the tip!  We'd still like to be able to use 2fa codes to protect certain views though, not just passwords...

**Comment by moggers87** [comment]
Also, I don't think `SetupView` actually creates backup token by default - that's in `BackupTokensView`. So just don't use that view and write your own that displays the tokens once and once only.

**Comment by Bouke** [comment]
Adding to @moggers87, you could create a view similar to `BackupTokensView` that only generates a new set of backup tokens after the user clicks a button. That would invalidate any prior backup tokens and generate 10 new backup tokens.

You should be able to define your own views, or configure the default ones, to suit your needs. Django introduced ClassBasedViews to enable these use-cases. The defaults are provided by this package, but it's up to you to configure them to your needs. So if you need to override `success_url`, go ahead. Or if you don't want to use the stock `BackupTokensView`, please do so and provide custom `urlpatterns`.

**Comment by hjwp** [comment]
thanks for the tips everyone!  (particularly @moggers87 re: django-sudo).  I think, given that no-one else seems to be requiring re-auth by 2fa tokens, we may have been slightly overdoing it.  going to close this for now... anyone else interested can of course reopen!
