### ISSUE TITLE
Authentication backend's authenticate() method is called 3 times during a successful authentication

### ISSUE THREAD

**Issue by hsenot** [Bouke/django-two-factor-auth#221]
## Current Behavior

I am using this package with a custom authentication backend and logging the calls to the authenticate() method. It seems there are 3 calls to authenticate() during a successful authentication (instead of 1).

## Possible Cause

The formtools wizard post() method called from IdempotentSessionWizardView's [post()](https://github.com/Bouke/django-two-factor-auth/blob/master/two_factor/views/utils.py#L138) contains 3 direct or indirect calls to form.is_valid():

1. `if form.is_valid():` [here](https://github.com/django/django-formtools/blob/master/formtools/wizard/views.py#L301)

2. `self.steps.last` [here](https://github.com/django/django-formtools/blob/master/formtools/wizard/views.py#L307)

3. `return self.render_done(form, **kwargs)` [here](https://github.com/django/django-formtools/blob/master/formtools/wizard/views.py#L309)

Each of these 3 calls is triggering a form.is_valid() call, and as a consequence, an authentication backend authenticate() call.

I am a bit unsure if this issue is better addressed in this project, in formtools or in contrib.auth's AuthenticationForm. I think the root cause is the use of contrib.auth's AuthenticationForm within the formtools wizard.

## Steps to Reproduce (for bugs)

1. Create a custom authentication backend based on the default ModelBackend https://github.com/django/django/blob/master/django/contrib/auth/backends.py#L7-L103
2. Log calls to authenticate()
3. Login successfully (even with a non-2FA user) and check the log for 3 calls to authenticate()

## Context

In the context of a remote user authentication backend, 3 external API calls to a remote server can add significantly to the time needed for logging in - it degrades performance and scalability.

## Your Environment

* Python version: 3.4
* Django version: 1.11.1
* django-two-factor-auth version: 1.6.2

**Comment by Bouke** [comment]
There have been talks about replacing the LoginView with a custom design, dropping the Wizard from formtools. For normal use-cases the additional calls to authenticate should not be a problem, but for certain use-cases (like yours) I can see that the current situation is not ideal. However replacing the form isn't something that is actively being worked on (as far as I know), but two proposals have been made: #193 and #194.

**Comment by moggers87** [comment]
I believe this has been fixed in 1.12.0.
