### ISSUE TITLE
Can two-factor be combined with social logins?

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#23]
@todo investigate if/how two-factor can be combined with social logins, like OpenID / Oauth (Facebook/Twitter). Is special care required, or is it uncommon to do so?

**Comment by PetrDlouhy** [comment]
For anyone looking to this I have made [dj-2fa-social-auth](https://pypi.org/project/dj-2fa-social-auth/) application which makes this easier to implement in connection with [social-app-django](https://github.com/python-social-auth/social-app-django).
