### ISSUE TITLE
How to override get_available_phone_methods() ?

### ISSUE THREAD

**Issue by goetzk** [Bouke/django-two-factor-auth#233]
Hi,
I'm trying to add another (couple of) authentication sources and so I need to change get_available_phone_methods() allow items other than sms/phone/yubikey. I have already made django_otp Device model classes for my new sources added devices for each, testing in a python shell and minimal django they work and I'm now trying to figure out the upper layers - in this case, trying out two_factor.

If changing override get_available_phone_methods() turns out to be doable I'll investigate what changes are required to the UI code in order to expose the new devices for users to register their own.

thanks,
kk

**Comment by Bouke** [comment]
Hi there, I've been playing with the idea of introducing some sort of pluggable architecture, see also my comments in this bug report: #215.

**Comment by goetzk** [comment]
On 4 November 2017 7:04:52 am AEDT, Bouke Haarsma <notifications@github.com> wrote:
>Hi there, I've been playing with the idea of introducing some sort of
>pluggable architecture, see also my comments in this bug report: #215.

Thanks for the pointer!
It does look like the best path forward but I am not sure I will have time to attempt that work in my current project.
I will subscribe to the other issues but probably hack in support for now.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
