### ISSUE TITLE
Question: Is django-two-factor-auth==1.6.2 compatible with Django==2.0?

### ISSUE THREAD

**Issue by compsult** [Bouke/django-two-factor-auth#237]
Trying to get django-two-factor-auth==1.6.2 comatible running with Django==2.0

## Current Behavior

urls.py code:
urlpatterns = [     url(r'', include(tf_urls + tf_twilio_urls, 'two_factor')), ]
results in this error:
   re_path(r'', include(tf_urls + tf_twilio_urls, 'two_factor')),
  File "/home/compsult/Data/SoftwareDev/PF20/lib/python3.5/site-packages/django/urls/conf.py", line 39, in include
    'Specifying a namespace in include() without providing an app_name '
django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Browser and version: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Python version: 3.5.2
* Django version: 2.0
* django-otp version:0.4.1.1
* django-two-factor-auth version: 1.6.2
* Link to your project: (private)

**Comment by Bouke** [comment]
The current version on pypi doesn’t work with 2.0, but master should work. Can you try that and report back how that works for you?

**Comment by compsult** [comment]
The master did not appear to help. I was getting this error:
 re_path(r'', include(tf_urls + tf_twilio_urls)),
  File "/home/compsult/Data/SoftwareDev/PF20/lib/python3.5/site-packages/django/urls/conf.py", line 17, in include
try:
django.core.exceptions.ImproperlyConfigured: Passing a 4-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.

In the debugger, I can see that tf_urls + tf_twilio_urls was resulting in a 4-tuple (below), which Django does not like

([<URLPattern '^account/login/$' [name='login']>
 <URLPattern '^account/two_factor/setup/$' [name='setup']>
 <URLPattern '^account/two_factor/qrcode/$' [name='qr']>
 <URLPattern '^account/two_factor/setup/complete/$' [name='setup_complete']>
 <URLPattern '^account/two_factor/backup/tokens/$' [name='backup_tokens']>
 <URLPattern '^account/two_factor/backup/phone/register/$' [name='phone_create']>
 <URLPattern '^account/two_factor/backup/phone/unregister/(?P<pk>\d+)/$' [name='phone_delete']>
 <URLPattern '^account/two_factor/$' [name='profile']>
 <URLPattern '^account/two_factor/disable/$' [name='disable']>]
 'two_factor'
 [<URLPattern '^twilio/inbound/two_factor/(?P<token>\d+)/$' [name='call_app']>]
 'two_factor_twilio')


So I tried splitting the tf_urls + tf_twilio_urls intro 2 statements and the angels sang
re_path(r'', include(tf_urls)),
re_path(r'', include(tf_twilio_urls)),

**Comment by cgoss** [comment]
I get past this by just doing an include on tf_urls. 

 url(r'', include('tf_urls')),
or
 url(r'', include('two_factor.urls')),

However when it gets to displaying the view it throws a namespace exception

**Comment by cgoss** [comment]
I get the following error. 


Request Method: | GET
-- | --
http://localhost:8000/
2.0
NoReverseMatch
'two_factor' is not a registered namespace


32 | <a href="{% url 'home' %}">{% trans "Home" %}</a></li>
-- | --
<li class="{% block nav_secret %}{% endblock %}">
<a href="{% url 'secret' %}">{% trans "Secret Page" %}</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
{% if user.is_authenticated %}
<li><a>{{ user }}
{% if user.otp_device %}<span class="glyphicon glyphicon-lock"></span>{% endif %}
</a></li>
<li class="{% block nav_profile %}{% endblock %}">
<a href="{% url 'two_factor:profile' %}">{% trans "Account Security" %}</a></li>
<li class="{% block nav_sessions %}{% endblock %}">
<a href="{% url 'user_sessions:session_list' %}">{% trans "Sessions" %}</a></li>
<li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
{% else %}
<li><a>{% trans "Not logged in" %}</a></li>
<li><a href="{% url 'two_factor:login' %}">{% trans "Login" %}</a></li>
{% endif %}
</ul>
</div>
</div>

**Comment by cgoss** [comment]
I got past this with the following .

`tf_pattern=(tf_urls,'two_factor')
urlpatterns = [
    url(r'', include(tf_pattern, namespace='two_factor')),
  
]
`

**Comment by Bouke** [comment]
The documentation lists these installation instructions:

> Add the routes to your project url configuration:
```python
urlpatterns = [
    url(r'', include('two_factor.urls', 'two_factor')),
    ...
]
```

Wouldn't that work for you as well?

**Comment by compsult** [comment]
I could be wrong, but I was not able to get that to work. For Django 2, only by splitting that line into 2 lines was I able to get the code to work
```
urlpatterns = [
    url(r'', include('two_factor.urls', 'two_factor')),
    ...
]
```

into this...

```
re_path(r'', include(tf_urls)),
re_path(r'', include(tf_twilio_urls)),
```
