### ISSUE TITLE
1.7.0 updates drops Django 1.8 compatibility

### ISSUE THREAD

**Issue by es-kan** [Bouke/django-two-factor-auth#238]
## Issue

Importing from `django.utils.deprecation` without catching the ImportError means that this package does not work on older versions of Django anymore. I noticed 1.8 isn't mentioned in the readme, but it would be unfortunate if you hadn't planned on dropping it.

## Your Environment

* Python version: 2.7
* Django version: 1.8
* django-otp version: 0.4.2
* django-two-factor-auth version: 1.6.2 because of this.

**Comment by Bouke** [comment]
Compatibility with Django <1.11 is indeed dropped, see also the [release notes](http://django-two-factor-auth.readthedocs.io/en/stable/release-notes.html).
