### ISSUE TITLE
How to simulate a OTP verified user for Django automated testing?

### ISSUE THREAD

**Issue by hoarderjohn2** [Bouke/django-two-factor-auth#244]
I am trying to implement Django's automated testing, against pages with @otp_required decorators. However, I can't seem to simulate an OTP-verified user.

Django itself has a test client with a function to simulate logins:
`self.client.force_login(user)`
and
`self.client.login(username='testuser', password='12345')`

However, I can't seem to do the same for the OTP verification with the test client. There doesn't seem to be any function available for such automated testing. Any solutions?

```
class ViewTests(TestCase):

    def test_view_page(self):
        user = create_user()
        self.client.login(username='testuser', password='12345')


        #### OTP Verification should happen here ####


        response = self.client.get(reverse('testpage'))
        self.assertEqual(response.status_code,200)
    
```

**Comment by moggers87** [comment]
You just need to populate the session with data that OTPMiddleware is looking for:

```
# you can use any OTP device, but StaticDevice is the easiest to use.
device = StaticDevice.objects.get_or_create(user=user)[0]

self.client.session[DEVICE_ID_SESSION_KEY] = device.persistent_id
self.client.session.save()  # not sure if this is required, but I do it anyway
```

**Comment by Bouke** [comment]
Thanks Matt! This is similar to what the [test cases](https://github.com/Bouke/django-two-factor-auth/blob/7684b9a08f63ffa0ee79c3ac94a0f67ba864730a/tests/utils.py#L39) do as well.
