### ISSUE TITLE
Qr code not rendering

### ISSUE THREAD

**Issue by khanzf** [Bouke/django-two-factor-auth#246]
I am not having Qr codes fail to render. Chromium and Firefox present a broken image. There is no error message in the Django dev server.
I suspect it is happening in two_factor/views/core.py I suspect towards the end at 561.
The size of the qrcode.make(), HttpResponse() and img.save() seem to return correctly. Specifically, I can do resp.content will print out.
What is causing this issue?

My environment is this:
- two_factor
- django_extensions
- django-two-factor-auth
- django-otp-yubikey
- Werkzeug
- pyOpenSSL
- django-otp
- django-two-factor-auth

I am running the dev-server as follows:
./manage.py runserver_plus --cert /tmp/ 0.0.0.0:8000

**Comment by khanzf** [comment]
I just double-checked this, it only fails when I run runserver_plus (TLS), but not when I run a standard HTTP dev server. I do not know where this issue may lay, if its specific to the django-two-factor-auth project or elsewhere.

**Comment by Bouke** [comment]
If there's no error, there's little to go by. I suggest running the code with a debugger, set breakpoints and investigate where a possible issue might be. Also using your browser's developer console to inspect responses from the webserver could be helpful here.

**Comment by khanzf** [comment]
I ran my connection through BurpSuite. The HTTP headers are the same, including the content-length, but the actual content on an HTTPS connection is 0 bytes.
Is there a way to debug where the issue may originate?

**Comment by Bouke** [comment]
You could use an interactive debugger like PyCharm / VSCode to see what is going on in the code. A good place to start looking is where the code is being rendered, and trace back from there.

**Comment by Bouke** [comment]
Closed inactive issue.
