### ISSUE TITLE
Add "Trust this computer for {given-number-of}" days option

### ISSUE THREAD

**Issue by barseghyanartur** [Bouke/django-two-factor-auth#250]
### First time login scenario
**Given** That user had set up two-factor auth
**And** Successfully logged in using username and password
**And** Successfully confirmed authentication with OTP from his token generator device/SMS 
**Then** Give user an option to "Trust this computer for {given-number-of} days"
**And** Authenticate user  

### Second time login scenario
**Given** That user had set up two-factor auth
**And** Successfully logged in using username and password
**And** User had used an option to "Trust this computer for {given-number-of} days"
**And**  Attempt to login falls within the {given-number-of} days 
**And** Authenticate user  

## Current Behavior
User is being asked for OPT every time he logs in.

## Possible Solution
Add an option to "Trust this computer for {given-number-of} days".

**Comment by Bouke** [comment]
This would be a very nice feature to have. Duplicate of feature request #56.

**Comment by diegobill** [comment]
:+1:
