### ISSUE TITLE
Issue with QR Code Validation

### ISSUE THREAD

**Issue by LuckyLion777** [Bouke/django-two-factor-auth#259]
## Current Behavior
Currently the code is implemented to use otpauth_url as data for generating QR Image,
And otpauth_url is like this: 

"otpauth://totp/127.0.0.1%3A8000%3A%20superuser?secret=ZE26FZ**********2EOEW&digits=9&issuer=127.0.0.1%3A8000".

It contains digits and also characters.
But token input field (which users input token) is INTEGER field, so that user can not enter above QR code after scanning since it contains characters.
How can I solve this?

## Your Environment

* Browser and version: Google Chrome, Version: 64.0.3282.140 (Official Build) (64-bit)
* Python version: 3.6.4
* Django version: 2.0
* django-otp version: 0.4.2
* django-two-factor-auth version: added two_factor to my project as local django app.

**Comment by Bouke** [comment]
Please provide steps to reproduce, I don't quite understand your question.

**Comment by LuckyLion777** [comment]
In a nutshell, I got this result when I scanned QR Image on your heroku app.

"otpauth://totp/127.0.0.1%3A8000%3A%20superuser?secret=ZE26FZ**********2EOEW&digits=9&issuer=127.0.0.1%3A8000".

I have to enter this string to token input field, but token input field is accepting only digits.
Can not input string since it contains chracters.

Should I attach screenshot?

Thanks.

**Comment by Bouke** [comment]
I think you don't understand what the QR code's supposed to do. That QR code contains the secret (seed value) used by an OTP generator to generate an actual 6/8 digit code. So you have to install something like Google Authenticator (or any other OTP generator) on your phone and use that app to scan the QR code. After having done that, the OTP generator app will provide you with a (in this instance) 6 digit code, which you enter in the token field.
