### ISSUE TITLE
Use email address as username

### ISSUE THREAD

**Issue by jfschaff** [Bouke/django-two-factor-auth#266]
Hi, out of the box, Django does not provide a simple way of using an email address instead of a username despite that fact that this has become common practice on the web. I have already implemented that in my project and would like to use django-two-factor-auth now.

From the doc, it seems like this is not already in django-two-factor-auth. Would you consider integrating this feature if I submit a pull request?

**Comment by moggers87** [comment]
I don't think that's necessary as you can easily override [`LoginView.form_list`](https://github.com/Bouke/django-two-factor-auth/blob/8294070cd3107bd88a780729064a5e09cff67819/two_factor/views/core.py#L63-L67):

```
from two_factor.views.core import LoginView

# you could subclass LoginView to do the same if you prefer
login_view = LoginView.as_view(form_list=(
   ('auth', MyForm),
   ('token', AuthenticationTokenForm),
   ('backup', BackupTokenForm),
))

```

…and then just use that in your urlconf.

**Comment by moggers87** [comment]
The default user model is part of Django, not Django-Two-Factor-Auth. My assumption was that you'd created a custom model with a custom auth form, so you needed replace the default auth form with yours.

Alternatively, if you've set `AUTH_USER_MODEL` to be your custom user model [you can set `USERNAME_FIELD` to point to the email field](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#specifying-a-custom-user-model) and you won't have to override anything in django-two-factor-auth at all.

**Comment by jfschaff** [comment]
Ok I get it, thanks.
