### ISSUE TITLE
Override two_factor/_base.html doesn't seem to be working

### ISSUE THREAD

**Issue by swkshannon** [Bouke/django-two-factor-auth#275]
Whenever I override two_factor/_base.html nothing happens, am I missing something? Is there a setting or anything like that?

there is only one line in the  two_factor/_base.html file: 

{% extends "_base.html" %}

I just want to keep my normal _base.html.

## Expected Behavior
I would expect to see all of the formats to change.

## Current Behavior
Nothing changes and I still see the message that says:

"Provide a template named two_factor/_base.html to style this page and remove this message."

## Context
I'm building a django website where I would like to force 2 factor authentication.
I would just like google authenticator functionality.

## Your Environment

* Browser and version:
* Python version 3.6:
* Django version 2:
* django-otp version latest :
* django-two-factor-auth version latest:

**Comment by RobotKernel** [comment]
I've got the same issue, can't seem to override the base template.

**Comment by ethanpobrien** [comment]
I was able to do it by just putting a folder named two_factor in my /templates/ folder, and inside two_factor/ i put my customized _base.html and it overwrote theirs with css and things but kept their way of leading you from login to token entry

**Comment by Bouke** [comment]
Try running the example app provided with this project. It shows how the template can be overridden. Tested and verified on Django 2.1.

**Comment by jrsperry** [comment]
@Bouke In the example app I can see that the file is overwritten but I have no clue how this is set up in the actual code itself. Where can I find the code to the example app?

**Comment by moggers87** [comment]
In the `example` directory: https://github.com/Bouke/django-two-factor-auth/tree/master/example

**Comment by naowal** [comment]
I served it by copy templates/two_factor from
https://github.com/Bouke/django-two-factor-auth/tree/master/two_factor/templates/two_factor
and paste in the templates that it own path refer to.
And Try to remove message "Provide a template named
    <code>two_factor/_base.html</code> to style this page and remove this message."
If it not show anymore when runserver. That's work!
