### ISSUE TITLE
Auth only use SMS?

### ISSUE THREAD

**Issue by mmmcorpsvit** [Bouke/django-two-factor-auth#279]
I search way for simple replace standart Django e-mail auth replace more progresive SMS.

How i see:

1. login page: phone + pin
2. register page: phone -> send SMS -> use enter PIN
3. restore page: enter phone number -> just resend PIN
4. change PIN page: enter old + enter new PIN -> resend PIN

i newbey on you package, are this possible use you package? Or maybe have shortest way for this? I already see Twilio, nice, but i will use custom send SMS backend.

In real i wont integrate SMS auth in Django Saleor

Th!

**Comment by Bouke** [comment]
From what I understand of your question, you want to replace password with a pin. So this means that you don't introduce a second factor. This package provides two-factor authentication, so isn't a fit for your use-case.
