### ISSUE TITLE
Default Templates does not work with CSP

### ISSUE THREAD

**Issue by xkill** [Bouke/django-two-factor-auth#285]
If you enable CSP without unsafe-inline the default templates does not work.

Reproduce it:
Enable two_factor and django_otp for admin site following Installation instrucctions.
Enable django-csp middleware.
Create a Login template.
Try it.
It does not work because unsafe-inline is not enabled.

**Comment by moggers87** [comment]
django-csp is a third party package and as you pointed out it will work if `'unsafe-inline'` added to the style directive.

Pull requests are always welcome ☺

**Comment by moggers87** [comment]
This can be closed now as templates no longer use inline styles since #386 was merged
