### ISSUE TITLE
Requested step 'token' is no longer valid, returning to last valid step in the wizard.

### ISSUE THREAD

**Issue by ZedObaia** [Bouke/django-two-factor-auth#291]
## Session flush between wizard steps
I get this error `Requested step 'token' is no longer valid, returning to last valid step in the wizard.`
When I use chromium or opera, however it works fine with firefox.
My best guess is that the token is saved in session, and somehow the sessions get flushed ?

## My Environment
* Browser and version: Oprta 58.0.3135.53 - Firefox 65.0 (64-bit), Chromium : 71.0.3578.98
* OS : Ubuntu 18.04
* Python version: Python 3.6.7
* Django version: Django==2.1.5
* django-otp version: django-otp==0.5.1
* django-two-factor-auth version: django-two-factor-auth==1.8.0

**Comment by moggers87** [comment]
[This comment](https://github.com/Bouke/django-two-factor-auth/issues/65#issuecomment-57931565) might explain what's happening. Check the requests your browser is making to see if there's something being fetched that requires the user being logged in.

**Comment by ZedObaia** [comment]
Thank you, @moggers87 
That's exactly what' been happening, chrome/opera requests favicon.ico automatically before the token step which goes through a `login_required` view as, what I did is adding this url to my `urlpatterns` to escape the favicon request
`re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico'))`
Which solves the issue

**Comment by moggers87** [comment]
With that solved I'm closing this issue.

**Comment by ivorbosloper** [comment]
Django 5.1 has a new feature [LoginRequiredMiddleware](https://docs.djangoproject.com/en/5.1/ref/middleware/#django.contrib.auth.middleware.LoginRequiredMiddleware) that turns on login-protection for **all** views. If you enable this, the fix above works with a slight modification:

```
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_not_required

urlpatterns = [
    ...
    re_path(r'^favicon\.ico$', login_not_required(RedirectView.as_view(url='/static/favicon.ico')))
]
```
