### ISSUE TITLE
How do I enable 2FA for a User

### ISSUE THREAD

**Issue by a1ec** [Bouke/django-two-factor-auth#292]
I have followed the documentation and cannot see how to enable 2FA for a user within the API.
`./manage.py two_factor_status 'brett.g@kidsinc.com'`
`brett.g@kidsinc.com: disabled`

It's sounds very basic, what am I missing here?

## Expected Behavior

I am expecting to see some reference to enabling 2FA for a user within the documentation.

## Current Behavior

There is no reference to enabling 2FA for a user within the documentation.

## Possible Solution

Add a reference to enabling 2FA for a user within the documentation.

## Steps to Reproduce (for bugs)

Installed and configured as per documentation at: https://django-two-factor-auth.readthedocs.io/en/stable/installation.html

I removed existing auth routes 'django.contrib.auth.urls' (and added a logout route based on the provided example).
The django-two-factor-auth views are displaying and I can login however there is no request for an OTP at any point. When I click Next button on login page, I am expecting OTP entry request but my user is authenticated to the admin portal / app.

When I check status I get:
`./manage.py two_factor_status 'brett.g@kidsinc.com'`
`brett.g@kidsinc.com: disabled`

## Context

I am trying to use the framework to add 2FA to user authentication.

For what it's worth, this is my User model.
```
`from django.contrib.auth.models import AbstractUser
....

class User(AbstractUser):
    organisation = models.ForeignKey('Organisation', null=True, on_delete=models.CASCADE)`

```
## Your Environment

* Browser and version: Firefox Quantum 65.0
* Python version: 3.6.8
* Django version: 2.1.7
* django-otp version: 0.5.2
* django-two-factor-auth version:
* Link to your project:

**Comment by a1ec** [comment]
I entered a non-existent route and was given some routes I was not familiar with:
tfa ^account/login/$ [name='login']
**tfa ^account/two_factor/setup/$ [name='setup']**
tfa ^account/two_factor/qrcode/$ [name='qr']
tfa ^account/two_factor/setup/complete/$ [name='setup_complete']
tfa ^account/two_factor/backup/tokens/$ [name='backup_tokens']
tfa ^account/two_factor/backup/phone/register/$ [name='phone_create']
tfa ^account/two_factor/backup/phone/unregister/(?P<pk>\d+)/$ [name='phone_delete']
tfa ^account/two_factor/$ [name='profile']
tfa ^account/two_factor/disable/$ [name='disable'] 

I was looking for:
**tfa ^account/two_factor/setup/$ [name='setup']**

The package is working well, thank you 👍

**Comment by Benjamin-Kozuch** [comment]
Thank you for that!
