### ISSUE TITLE
Compatibility issues with django 2.2

### ISSUE THREAD

**Issue by iw108** [Bouke/django-two-factor-auth#298]
## Problem
I have been using two_factor with Django 2.1 for a while without any problems (thank you for all your work!). However, I recently upgraded to Django 2.2 and am having some compatibility issues. Whilst I am still able to create ```PhoneDevice``` objects, I can now no longer delete them (both within the shell environment and the relevant views e.g. ```PhoneDeleteView``` and ```DisableView```). In both cases, I get the same error. For example, if I enter the following in the shell ``` PhoneDevice.objects.first().delete() ``` I get the following error:

``` console
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/iwilliams/.virtualenvs/twofactor/lib/python3.6/site-packages/django/db/models/base.py", line 918, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/home/iwilliams/.virtualenvs/twofactor/lib/python3.6/site-packages/django/db/models/deletion.py", line 192, in collect
    reverse_dependency=reverse_dependency)
  File "/home/iwilliams/.virtualenvs/twofactor/lib/python3.6/site-packages/django/db/models/deletion.py", line 94, in add
    if obj not in instances:
TypeError: unhashable type: 'PhoneDevice'
```

## Possible Solution
Part of the problem seems to lie with the following method:

``` Python
class PhoneDevice(Object):
   ...
    def __eq__(self, other):
        if not isinstance(other, PhoneDevice):
            return False
        return self.number == other.number \
            and self.method == other.method \
            and self.key == other.key
```
When the above function is commented out, I am able to remove PhoneDevice objects. Perhaps on a related note, I should note that I can add ```TOTPDevice``` and ```YubikeyDevice``` instances in Django 2.2 without a problem, both of which don't override the base ```__eq__``` method. 

Do you have any further insight into what is causing this problem/ how it can be properly resolved?

Thanks in advance!

## Environment Info
* Python version: 3.6.7
* Django version: 2.2
* django-otp version: 0.6.0
* django-two-factor-auth version: 1.8.0

**Comment by claudep** [comment]
From https://docs.python.org/3/reference/datamodel.html#object.__hash__:
`if it defines __eq__() but not __hash__(), its instances will not be usable as items in hashable collections.`

**Comment by moggers87** [comment]
Hmm, I wonder why that model defines `__eq__`? Do you know if any test fails if that method is commented out?

**Comment by Bouke** [comment]
I'm not entirely sure how it is used, but it was introduced here: https://github.com/Bouke/django-two-factor-auth/commit/893fb23781d670ad55c0bbd5fd794bf45d27ccdb, which was added to support Django 1.7: https://github.com/django/django/commit/6af05e7a0f0e4604d6a67899acaa99d73ec0dfaa.

**Comment by moggers87** [comment]
`tests.test_views_phone.PhoneSetupTest.test_setup` fails on line 58 if I remove it (which makes sense because it's asserting that a mock was called with a specific phone device)

**Comment by EmperorArthur** [comment]
Can confirm.  I can not remove phone devices or disable two factor.  Any time I try I receive:
>TypeError at /account/two_factor/backup/phone/unregister/2/
>
>unhashable type: 'PhoneDevice'
