### ISSUE TITLE
Drop support for Django 1.11?

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#303]
Currently the package is compatible with every supported version of Django currently available. Django 1.11 is rather outdated and I guess it prevents the codebase from improving / holding off on cleanup. I don't see a particular need to keep supporting this version, also as there's already a new LTS version available (2.2). 

@MarkusH @moggers87 what's your take on this? We could just drop 1.11 from the test matrix / readme, no immediate further work necessarily required.

**Comment by claudep** [comment]
I think that dropping Python 2 (which is implied by dropping Django 1.11) should come before that.

**Comment by claudep** [comment]
See #304

**Comment by moggers87** [comment]
1.11 doesn't go EOL until April 2020, so I'd prefer to see it stay supported until then at least. Ditto on Python 2 support.

**Comment by Bouke** [comment]
Django 3.0 is scheduled to be available from Jan 2020. It drops Python 2 support, no longer ship with six and there are probably additional changes required on our end to support it. So I think we shouldn't aim to support both Django 1.11 and 3.0 from the same codebase. I suggest that at some point later this year we would drop 1.11 support in the master branch and we would start accepting PRs to target 3.0.

**Comment by claudep** [comment]
It might be possible that Django 1.11 on Python 3 can still be supported along Django 3.0 with minimal effort. To be evaluated when 3.0 is released.

**Comment by moggers87** [comment]
@claudep by the time Django 3.0 is out, 1.11 will only have a few months of maintenance left. Not worth the effort at that point IMO.

**Comment by claudep** [comment]
After the recent release of django-formtools 2.2, looks like current code is compatible with Django 3.0, yay! #324

**Comment by Bouke** [comment]
With django-tfa 1.10 out the door, I'm all for dropping support for Django 1.11 in the master branch.

**Comment by claudep** [comment]
Looks like 853a648247840935d48024607c4a7e1eb956d672 did the job!

**Comment by moggers87** [comment]
So it did

**Comment by Bouke** [comment]
Finally :)
