### ISSUE TITLE
Do a point release

### ISSUE THREAD

**Issue by EmperorArthur** [Bouke/django-two-factor-auth#308]
While it's true several bugs have been fixed in master.  Those of us who don't/cant run directly off of master are still affected by them.  I propose issuing a point release, and possibly doing so regularly.

This is in comparison to the current trend of only doing major releases.

## Expected Behavior

My website works properly with the latest code via pip/pipenv.

## Current Behavior

Bug #298 still affects my website.

## Possible Solution

Do a point release from master.

## Other notes
0.18 was tagged, but not set as a release in GitHub.

**Comment by Bouke** [comment]
I've released 1.9.1 (would've been 1.9.0 if I hadn't messed up the changelog).
