### ISSUE TITLE
Customize Issuer in QRGeneratorView

### ISSUE THREAD

**Issue by ChristophRob** [Bouke/django-two-factor-auth#309]
If you want a different title than the site name, this is a quite uncomfortable change. You have to copy the whole get() method to achieve this.

## Expected Behavior
Easy change of the QRGeneratorView  issuer

## Current Behavior
Extreme hard change as you have to copy nearly the whole class.

## Possible Solution
```diff
class QRGeneratorView(View):
    ...

+   def get_issuer(self):
+       return get_current_site(self.request).name
+
    def get(self, request, *args, **kwargs):
       ...

        otpauth_url = get_otpauth_url(accountname=username,
-                                     issuer=get_current_site(self.request).name,
+                                     issuer=self.get_issuer(),
                                      secret=key,
                                      digits=totp_digits())
```

**Comment by moggers87** [comment]
Sounds good to me, pull requests welcome :smiley:

**Comment by ChristophRob** [comment]
@moggers87 
Cool, i just opened a pull request
