### ISSUE TITLE
translation in dutch

### ISSUE THREAD

**Issue by YvonneJanssen** [Bouke/django-two-factor-auth#311]
Translation of the following sentence is not right:
msgid ""
"We've sent a token to your phone number. Please\n"
"        enter the token you've received."
msgstr "We heb een token verzonden naar jouw telefoonnummer. Voer het token dat je hebt ontvangen."

Have to be:
msgstr "We hebben een token verzonden naar jouw telefoonnummer. Voer het token in dat je hebt ontvangen."

**Comment by Bouke** [comment]
Dankjewel! We use [transifex](https://www.transifex.com/Bouke/django-two-factor-auth/) to manage translations. I've updated the translation, it should be pulled in for the next release.
