### ISSUE TITLE
shows login page if you hit login url, even though already loggedin in other tab

### ISSUE THREAD

**Issue by praveenskumar** [Bouke/django-two-factor-auth#312]
**https://example-two-factor-auth.herokuapp.com/account/login/**

After successfully logged into the site after entering the token saved in google authenticator app. It will redirect to logged in page( dashboard).

But when you open new tab and try to account login url, it should not ask for login again again as i am already logged in the other tab?

**Comment by praveenskumar** [comment]
Invalid..

**Comment by chronicom** [comment]
override the dispatcher like below

    #redirect to the next page
    def redirectToNext(self, **kwargs):
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        if not is_safe_url(url=redirect_to, allowed_hosts=[self.request.get_host()]):
            redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
        return redirect(redirect_to)                           
    
    def dispatch(self, request, *args, **kwargs):

        #if the user has already verified then proceed to next page
        if self.redirect_authenticated_user and request.user.is_verified():
            return self.redirectToNext(**kwargs)

**Comment by statsconchris** [comment]
In my case this gives me:
`The view myapp.views.view didn't return an HttpResponse object. It returned None instead.`


whereas the default dispatcher do ave HttpResponseRedirect
```
def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)
```
