### ISSUE TITLE
2FA 

### ISSUE THREAD

**Issue by viralshah-HACK** [Bouke/django-two-factor-auth#317]
We  trying to config for 2FA on one login ? Do we configure Djongo on one login ? 
or Do you have documentation how to do it with one login?

**Comment by moggers87** [comment]
Are you asking if two factor login can be done in one request? No, not out of the box.

If you limit your users to one specific type of 2FA (e.g. TOTP devices) you might be able to make your own login view that handles the username, password, and 2nd factor all in one go.

**Comment by viralshah-HACK** [comment]
No. I am not asking that.

**Comment by viralshah-HACK** [comment]
Do this application using
SAML federation or  IDP Federation ?

**Comment by moggers87** [comment]
I don't know what either of those are, but this package has nothing to do with federation.

**Comment by viralshah-HACK** [comment]
i Just mailed you our product description. i hope is easy to understand. Please reply me back.

**Comment by moggers87** [comment]
A quick Google search for "onelogin django" gave me this: https://github.com/onelogin/python-saml

I think that's probably what you want.
