### ISSUE TITLE
Please release 1.9.1post0

### ISSUE THREAD

**Issue by Natureshadow** [Bouke/django-two-factor-auth#320]
Hi,

could you please tag and upload 1 new version, e.g. 1.9.1post0, so the change to the django-phonenumber-field dependency can be used and help make dependencies resolvable again?

Thanks!

**Comment by debdolph** [comment]
Any progress on this, @Bouke :)?

**Comment by Natureshadow** [comment]
Maybe @moggers87 can help ;).

I also posted a PR to allow the recently released django-phonenumber-field 4.0, which should not break anything

**Comment by moggers87** [comment]
I only have commit access, not PyPI access.

And folks: you can install from git, e.g.

```
pip install git+https://github.com/Bouke/django-two-factor-auth.git@63b9974115d05bb618a4dd042b49453ec5f8bdb7#egg=django-two-factor-auth
```

Where `63b9974115d05bb618a4dd042b49453ec5f8bdb7` is whatever you commit you want to install.

**Comment by Natureshadow** [comment]
This is a one-time workaround for development, yes.

**Comment by Bouke** [comment]
All in due time everyone. 👨🏼‍💻

:shipit: https://pypi.org/project/django-two-factor-auth/1.10.0/
