### ISSUE TITLE
Yubikey and token generator do nothing

### ISSUE THREAD

**Issue by darkpixel** [Bouke/django-two-factor-auth#345]
## Expected Behavior
On the "Enable Two Factor" wizard screen I am presented with two methods:
* Token generator
* YubiKey

When I select either option, I am taken to the setup screen for that particular option--token generator shows a QR code and Yubikey has a box where you can touch your YubiKey and fill in the token.

When the information is filled in and "Next" is pushed, I expect to see some sort of "You did it!" screen.

## Current Behavior
After hitting "Next" when setting up either option, I am redirected back to ```/account/two_factor/setup/``` and the wizard starts over.

## Steps to Reproduce (for bugs)
1. I followed the instructions from https://django-two-factor-auth.readthedocs.io/en/stable/installation.html 
2. The only item I skipped was the LOGIN_REDIRECT_URL.
3.  I created a ValidationService object using info I received by going here: https://upgrade.yubico.com/getapikey/

## Your Environment
* Browser and version: Chrome 79.0.3945.130 (Official Build) (64-bit)
* Python version: 3.6.7
* Django version: 3.0.4
* django-otp version: 0.8.1
* django-two-factor-auth version: 1.11.0

**Comment by moggers87** [comment]
Are any devices being created? You can check this via the shell if using `django_otp.devices_for_user`

Also, what happens if you set `LOGIN_REDIRECT_URL`? (it's meant to be optional by the way, I just want to rule it out as causing this issue)

**Comment by darkpixel** [comment]
I just tested with ```LOGIN_REDIRECT_URL = '/'```.
I just had a thought that it could be related to having a custom user object.
Ran:
```
u = DashboardUser.objects.get(pk=1) # my test account
>>> for d in devices_for_user(u):
...   print(d)
...
>>> 
```

**Comment by darkpixel** [comment]
I just looked at the sample site (http://example-two-factor-auth.herokuapp.com/account/two_factor/setup/) and it does the exact same thing.

**Comment by moggers87** [comment]
Weird, the example site works fine for me when I select token generator. Do you have any Chrome extensions installed that might be interfering?

**Comment by darkpixel** [comment]
Only about 11 billion. ;)
Let me see if I can track it down...

**Comment by darkpixel** [comment]
It was an extension called "Web Server Notifier" that I've had installed for years.  It would give you info on the remote web server (nginx, apache, IIS, etc...) and the tech stack on the remote end (Django, ASP.NET, PHP, etc...)

The link is no longer valid in the web store.  Maybe it got pulled for abuse...  I removed it and it's working now.  Mystery solved.  Thanks!
