### ISSUE TITLE
'User' object has no attribute 'is_verified'

### ISSUE THREAD

**Issue by tchimih** [Bouke/django-two-factor-auth#350]
## Current Behavior
Whenever the user login and try to activate his TOTP, the message pops:

`AttributeError at /account/two_factor/setup/complete/ 
'User' object has no attribute 'is_verified' `

## Your Environment

* Browser and version:
* Python version: 3.6
* Django version: 3.0.4
* django-two-factor-auth version: 1.7.0

**Comment by moggers87** [comment]
Do you have `django_otp.middleware.OTPMiddleware` in `MIDDLEWARE`?

**Comment by moggers87** [comment]
Also do you really have 1.7.0 installed? That's quite old and I doubt it works properly with Django 3.0

**Comment by tchimih** [comment]
Here is my middleware:

`
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

Sorry my django-two-factor-auth is at v. 1.11.0

Thanks in advance.
`

**Comment by moggers87** [comment]
You have `AuthenticationMiddleware` listed several times. Remove all but the first one and your issue should be fixed.

**Comment by tchimih** [comment]
That solved my problem. Thanks alot.
