### ISSUE TITLE
Yubikey support

### ISSUE THREAD

**Issue by cyli** [Bouke/django-two-factor-auth#36]
Hi!  I just want to thank you for your work on this!  It's pretty amazing.  I was wondering if Yubikey support would be added at any point, since django-otp also supports Yubikeys?

**Comment by pckapps** [comment]
Is the Yubikey option still working on the demo site? I bought [this](https://www.yubico.com/products/yubikey-hardware/fido-u2f-security-key/) Yubikey, but can't get it loaded. What should I fill in, in the Yubikey field?

**Comment by Bouke** [comment]
I believe that the current Yubikey support is for an older device (Yubico OTP?), not the Yubikey's that implement U2F. We have #86 and #215 for that.

**Comment by Wolf480pl** [comment]
@pckapps for me the demo does work with my Yubikey NEO, but the demo uses Yubico OTP and not U2F. AFAIK all newer Yubikeys other than the blue U2F-only one, support both U2F and Yubico OTP. You need to have one of your OTP slots configured in YubiOTP mode and loaded with a key thattap th is accepted by yubico servers. Then you focus the text field and tap your yubikey, it should type a one-time password for you.

Still, U2F support would be nicer.
