### ISSUE TITLE
Upgrade templates to Bootstrap 4

### ISSUE THREAD

**Issue by claudep** [Bouke/django-two-factor-auth#364]
Several buttons in this package templates are still using the `btn-default` style which is gone in Bootstrap 4. This means that those buttons are not decorated at all and don't look like buttons with Boostrap 4. The `btn-default` style could be kept for backwards compatibility, but a new class should be added on those buttons, maybe `btn-outline-secondary` (as there are no direct equivalents of `btn-default` in Boostrap 4 button styles).

**Comment by 9mido** [comment]
Bootstrap 4 is important, but why focus on it when we soon have to worry about Bootstrap 5? 

https://v5.getbootstrap.com/

**Comment by moggers87** [comment]
The base template in `two_factor` still uses Bootstrap 3. Maybe we should think about upgrading the whole lot to Bootstrap 4?

**Comment by moggers87** [comment]
@9mido negative. 5 is still in alpha and who knows when that will be released (4 spent ages in alpha/beta before having a proper release)

**Comment by claudep** [comment]
Yes, I think it should be nice to base the template on BS4. I'm unfortunately not familiar enough with bootstrap yet to do that properly myself.
