### ISSUE TITLE
Example app hosted on Heroku - anytime give invalid token during 2FA with token generator

### ISSUE THREAD

**Issue by MickMonkeyD** [Bouke/django-two-factor-auth#372]
I have tried the example app hosted on Heroku; I have scanned the qrcode generated with Google Authenticator but when I insert the token it says anytime that it is invalid.

## Expected Behavior
I am expecting that the token is correct. This because it seems that the qrcode scanned is correct ( the username is right in google Auth )
 
## Current Behavior
It gives always a token invalid message

## Steps to Reproduce (for bugs)
1.Register on example app on Heroku
2.Login
3.Enable 2FA with token generator app
4.Scan the qr code and insert the token generated by Google Auth

## Context
Just I am not sure if I have done something wrong or it is just browser issue...

## Your Environment
Example app on Heroku
Google Authenticator as app to generate tokens

* Browser and version:
- Firefox for Linux Mint version 79.0 64 bit
- Chrome version 84.0.4147.125

**Comment by MickMonkeyD** [comment]
I'm so sorry, it was just that my phone and the server was not in synch, just one minute before...now they are in synch and it works. Sorry again.

**Comment by moggers87** [comment]
No worries, it happens :laughing:
