### ISSUE TITLE
Please update the django-phonenumber-field dependency to allow version 5.0.0

### ISSUE THREAD

**Issue by Lionqueen94** [Bouke/django-two-factor-auth#387]
Please update the django-phonenumber-field dependency to allow version 5.0.0.
Currently only up to version 3.99 is allowed, and in the meantime version 4.0.0 and 5.0.0 came out in the past year.

**Comment by moggers87** [comment]
Are there any changes in those versions that might effect django-two-factor-auth users?

**Comment by syserr0r** [comment]
Not sure how your latest release can claim 'Django 3.1 support' when your dependencies do not.

Django 3.1 support was only added to django-phonenumber-field in 5.0 (see https://github.com/stefanfoulis/django-phonenumber-field/blob/master/CHANGELOG.rst)

**Comment by moggers87** [comment]
That changelog also claims that support for Django 2.2 has been dropped. Is that a mistake?

**Comment by moggers87** [comment]
Apparently yes, it is a mistake https://github.com/stefanfoulis/django-phonenumber-field/issues/382#issuecomment-684765218

**Comment by atkawa7** [comment]
ping @moggers87

**Comment by moggers87** [comment]
Closed by #401
