### ISSUE TITLE
Release 1.12.2?

### ISSUE THREAD

**Issue by claudep** [Bouke/django-two-factor-auth#394]
It would be great to have a new release of this package. My use case is that I contributed a French translation for the just released django-otp 1.0.1 and django-two-factor-auth latest release still blocks django-otp >0.99.

**Comment by moggers87** [comment]
Yup, it's on my TODO list

**Comment by moggers87** [comment]
Done https://pypi.org/project/django-two-factor-auth/1.13/

**Comment by claudep** [comment]
:tada:

**Comment by beckedorf** [comment]
Thanks! Could you add the GitHub Release on Github?
