### ISSUE TITLE
Reproducible crash on login attempt

### ISSUE THREAD

**Issue by jasconius** [Bouke/django-two-factor-auth#397]
I've encountered a reproducible crash in 1.13. This crash occurs when logging in with twilio integration, logging out, then attempting to log in again. In my case, I also check "remember this device for 30 days" but I am unclear if this is impacting the bug. I was able to reproduce this in two separate environments with the steps described.

I should note that once you get into this state it is apparently irrecoverable without CLI access, if you happen to do it on your SA account. I've found no way to overcome it, problem persists through application restarts.

*edit*

I've confirmed that this has to do with the "remember this device" designation. When testing in another browser I attempted to reproduce WITHOUT this setting and it was fine. As soon as I add this setting to the steps, it crashes.

Removing the option to set the 30-day remember box by removing the TWO_FACTOR_REMEMBER_COOKIE_AGE value from settings immediately fixes this issue.

## Expected Behavior
Authorization should occur normally.

## Current Behavior
Python crash, session not established.

## Steps to Reproduce (for bugs)
1. Set up 2-factor on an account with Twilio integration
2. Log out.
3. Log in again, provide a token and check "remember this device for 30 days".
4. Log out.
5. Attempt to log in again.
6. Crash will occur after login form submission

## Your Environment

* Browser and version: Chrome
* Python version: has happened in both 3.6 and 3.9 (stack trace is for 3.6)
* Django version: 3.1.2
* django-otp version:
* django-two-factor-auth version: 1.13

## Stack Trace

> Environment:

> 
> Request Method: POST
> Request URL: http://localhost/account/login/
> 
> Django Version: 3.1.2
> Python Version: 3.6.7
> Installed Applications:
> ['django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.humanize',
>  'localflavor',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'rest_framework_filters',
>  'django_filters',
>  'main',
>  'water',
>  'callcenter',
>  'public',
>  'widget_tweaks',
>  'raven.contrib.django.raven_compat',
>  'storages',
>  'silk',
>  'dal',
>  'dal_select2',
>  'django.contrib.admin',
>  'phonenumber_field',
>  'django_otp',
>  'django_otp.plugins.otp_static',
>  'django_otp.plugins.otp_totp',
>  'two_factor']
> Installed Middleware:
> ['raven.contrib.django.middleware.DjangoRestFrameworkCompatMiddleware',
>  'raven.contrib.django.middleware.SentryMiddleware',
>  'silk.middleware.SilkyMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django_otp.middleware.OTPMiddleware',
>  'two_factor.middleware.threadlocals.ThreadLocals',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'main.middleware.TimezoneMiddleware',
>  'main.middleware.PasswordChangeMiddleware']
> 
> 
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/views.py", line 36, in sentry_wrapped_callback
>     return callback(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/two_factor/views/core.py", line 380, in dispatch
>     return super().dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 244, in dispatch
>     response = super().dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/two_factor/views/core.py", line 144, in post
>     response = super().post(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/two_factor/views/utils.py", line 164, in post
>     return super().post(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 297, in post
>     self.storage.set_step_files(self.steps.current, self.process_step_files(form))
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 62, in current
>     return self._wizard.storage.current_step or self.first
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 67, in first
>     return self.all[0]
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 49, in all
>     return list(self._wizard.get_form_list())
>   File "/usr/local/lib/python3.6/site-packages/formtools/wizard/views.py", line 222, in get_form_list
>     condition = condition(self)
>   File "/usr/local/lib/python3.6/site-packages/two_factor/views/core.py", line 92, in has_token_step
>     not self.remember_agent
>   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/usr/local/lib/python3.6/site-packages/two_factor/views/core.py", line 350, in remember_agent
>     device.throttle_reset()
> 
> Exception Type: AttributeError at /account/login/
> Exception Value: 'PhoneDevice' object has no attribute 'throttle_reset'

**Comment by moggers87** [comment]
Thanks for the report!

Initial thoughts:

- Why is the cookie code even calling `device.throttle_reset`?
- Why doesn't `PhoneDevice` implement those methods?

I'll have a look at this tomorrow.

**Comment by beckedorf** [comment]
@moggers87 

> Why is the cookie code even calling `device.throttle_reset`?

To prevent brute force verification via the agent remember cookie. As a cookie is anyway linked to a `Device` the remember agent code reuses the throttle counter of the `Device` it is linked to.

> Why doesn't PhoneDevice implement those methods?

Good question. I think it is a security risk and it should be added.

I fixed the issue in PR #398. Another solution to fix this is to remove the throttling code from the agent remember cookie code. It would be pretty easy to do and security issues are limited. The token key in the cookie is quite long (hmac_sha256) and it should be pretty hard to brute force it. But in any case: We should add Throttling to PhonveDevide as this code is too short.

**Comment by moggers87** [comment]
Fixed by 046639c0c56f78ec6026fac8e29ed8b8d739c48c
