### ISSUE TITLE
Master branch behind version-1.13

### ISSUE THREAD

**Issue by claudep** [Bouke/django-two-factor-auth#399]
The latest release was done from the version-1.13 branch which has 4 more commits than the master branch.

@moggers87, is this wanted or just an oversight?

**Comment by moggers87** [comment]
I can't push to master directly. I did email @Bouke after the release, but I think he's been busy and hasn't had time to get around to pushing that branch to master yet.

**Comment by claudep** [comment]
If the rule is that a merge request needs an approval before being pushed to master, it's a good thing. But if only @Bouke can merge to master, then I'd consider this as a bug :-) (bus factor and all that). @Bouke, can we solve that?

**Comment by moggers87** [comment]
I can push to master if the commits have been reviewed, but I can't be both committer *and* reviewer. @Bouke doesn't have those restrictions being the repo owner, of course.

@claudep are you volunteering to become an additional maintainer? :wink:

**Comment by claudep** [comment]
I cannot claim to be knowledgeable in every part of this package, but for the parts that I know, I would be glad to help for reviews.

**Comment by claudep** [comment]
I guess this can now be closed.
