### ISSUE TITLE
Please release asap

### ISSUE THREAD

**Issue by Natureshadow** [Bouke/django-two-factor-auth#414]
django-two-factor-auth has been incompatible with a lot of other projects for quite a long time now, specifically due to its ancient dependency on django-phonenumberfield. This seems to be fixed in master. Please make at least a patch release that fixes the dependency as soon as possible.

**Comment by moggers87** [comment]
I am unaware of any incompatibilities with other projects, so I don't see any great urgency in doing a release.

Are you unable to install from git directly?

**Comment by Natureshadow** [comment]
Hi,

>I am unaware of any incompatibilities with other projects, so I don't see any great urgency in doing a release.

Any other project that keeps its dependencies up to date is affected.

>Are you unable to install from git directly?

Yes, like anyone else doing serious software development. Dependencies from some git remote are not an option.

Please release your software so others can depend on it!

**Comment by moggers87** [comment]
> Any other project that keeps its dependencies up to date is affected.

That's an incompatibility with policy, not another package on PyPI.

> > Are you unable to install from git directly?
> Yes, like anyone else doing serious software development. Dependencies from some git remote are not an option.

There's no need for snide remarks. If you really can't install from git, then I would suggest you vendor this package until we do a release.

I'm closing this issue. We will release when we're ready and there are other issues I would like to be fixed before making another release.

**Comment by Natureshadow** [comment]
>I'm closing this issue. We will release when we're ready and there are other issues I would like to be fixed before making another release.

You can actually make more than one release within any period of time. Making a release nornally is as simple as `git tag - s`.

But ok, I will fork and upload to PyPI under a different name if you prefer that. I do not think it makes the situation better for anyone, but maybe better than having everyone wait until you have collected enough changes to release.
