### ISSUE TITLE
Can we please release the code changes since 1.13?

### ISSUE THREAD

**Issue by clearyusc** [Bouke/django-two-factor-auth#415]
This package will not allow us to "remember device for up to X days" until the latest code changes, which are in master, are released.

**Comment by moggers87** [comment]
I haven't had much time for this project recently, and I was hoping to get Django 3.2 support in before doing another release.

Given that there is an actual bugfix in master though, I'll see if I can get a release out in the next couple of days.

**Comment by moggers87** [comment]
1.13.1 has been released! :tada:
