### ISSUE TITLE
Backup tokens stored as plain-text

### ISSUE THREAD

**Issue by kurtdevos** [Bouke/django-two-factor-auth#416]
I'm no expert but,

Backuptokens act like passwords, they allow you to login. 
Unlike the Django passwords, backuptokens are stored unencrypted in the database. If a database is somehow leaked, all security tokens are leaked with it.
Shouldn't backuptokens be treated the same way as passwords ? ( < algorithm>$< iterations>$< salt>$< hash> )

**Comment by moggers87** [comment]
This has already been proposed upstream: https://github.com/django-otp/django-otp/issues/68

There is also a similar feature request for encrypting TOTP keys: https://github.com/django-otp/django-otp/issues/67

Closing this as any work to solve this issue really needs to be done in django-otp
