### ISSUE TITLE
About Transifex

### ISSUE THREAD

**Issue by gabriel-tessier** [Bouke/django-two-factor-auth#420]
Not really an issue but just to inform about activity on transifex (I am not a bot!!) 

There's 3 new language requests (1 is Russian and already exist, so maybe a mistake), still 2 requests.

Is there a way for somebody to validate the request before the requester leave! 

Thanks!

**Comment by claudep** [comment]
Unfortunately, Transifex allows for weird and/or duplicate language requests. Typically `<lang>_<country>` codes are only commonly used for very specific cases (pt_BR, for example). So the current requests are not valid in my opinion. I used to close them in the past, just to see the same coming again later, so I'm not bothering any longer for those requests, sorry.

**Comment by claudep** [comment]
Note that if you want a Japanese team, use the simple `ja` code, not `ja_JP`.

**Comment by gabriel-tessier** [comment]
@claudep 
Thank you for the information I submitted a new request for ja. I didn't find a way to cancel the previous request. 
Sorry for the noise. m(__)m

**Comment by claudep** [comment]
I just remember I'm not an admin on this project on Transifex, so cannot approve anything. @moggers87, looks like your call...
I also saw that there are already `<lang>_<country>` codes (like he_IL, that should be he).

**Comment by moggers87** [comment]
Last time I logged in, I didn't have that sort of access. Passing this one onto @Bouke

**Comment by Bouke** [comment]
@moggers87 @claudep I've made you both maintainers on Transifex 👍

**Comment by claudep** [comment]
Thanks a lot. Japanese team approved!

**Comment by gabriel-tessier** [comment]
Thanks for the support! 
I think that now I can close the issue!
