### ISSUE TITLE
How to enforce website logo to the token generator apps?

### ISSUE THREAD

**Issue by rez0n** [Bouke/django-two-factor-auth#429]
Hi, probably off-topic question, but does anybody has an idea how to enforce website logo image to get picked by token generator applications such as Authy?

Actually, Authy pick one of the flags images from the static folder

> I was read in the Authy docs that Google Images is used to find website logo, but actually, the image picked by Authy does not appear in the search, looks like Authy pick first loaded image on the website index page or something like that.

Thanks in advance.

**Comment by moggers87** [comment]
This doesn't sound like something we can help with, especially if the app is using Google Images to find a logo.

**Comment by rez0n** [comment]
Got it, thanks. I hoped you'll have some "lifehacks" for this.
