### ISSUE TITLE
Django 1.8: No module named 'django.contrib.formtools'

### ISSUE THREAD

**Issue by troygrosfield** [Bouke/django-two-factor-auth#89]
When updating to the newly released django 1.8, you see the following error:

```
  File "/python3.4/site-packages/two_factor/models.py", line 18, in <module>
    from .gateways import make_call, send_sms
  File "/python3.4/site-packages/two_factor/gateways/__init__.py", line 2, in <module>
    from ..compat import import_by_path
  File "/python3.4/site-packages/two_factor/compat.py", line 5, in <module>
    from django.contrib.formtools.wizard.views import WizardView
ImportError: No module named 'django.contrib.formtools'
```
See: https://docs.djangoproject.com/en/1.8/releases/1.8/#removal-of-django-contrib-formtools

All the fixes for this change can be found here:

- https://docs.djangoproject.com/en/1.8/ref/contrib/formtools/#formtools-how-to-migrate

**Comment by Bouke** [comment]
I'm currently investigating on how to support Django 1.8, while maintaining support for older Django versions.

**Comment by griphiam** [comment]
If you still want to use the library, the way I've seen it done in the past is with conditional imports (since they say the classes are the exact same).

    try:
        from formtools.wizard.views import WizardView
    except ImportError, e:
        from django.contrib.formtools.wizard.views import WizardView

**Comment by Bouke** [comment]
Thanks; support for Django 1.8 has been added. If no issues are found, a new version will be released.
