### ISSUE TITLE
Wizard should skip method selection if only one method

### ISSUE THREAD

**Issue by tecknicaltom** [Bouke/django-two-factor-auth#93]
If you follow the default installation and have not yet added Twilio support, the only 2FA method will be the Token generator. When enabling 2FA for an account, one of the screens of the wizard prompt you to choose an authentication method. If there is only one method available, this screen should be skipped.

**Comment by Bouke** [comment]
Thanks for reporting. I'm thinking about moving the phone/sms support out of the package, into a separate package. However I for the time being, you could look into customizing the views, or even provide a PR?

**Comment by MarkusH** [comment]
This seems fixed

**Comment by ikatza** [comment]
I don't have enabled the phone methods (just the token generator) and the text related to the backup phone numbers in the profile template still appears. 

What in the demo app reads: 
>**Backup Phone Numbers**
> If your primary method is not available, we are able to send backup tokens to the phone numbers listed below.

The button doesn't appear. I'm using the translated version to spanish.

Is there a way to remove such text?

**Comment by Bouke** [comment]
Ah that's a bit strange. I've logged #224 for this. As a workaround you could override the template, where  you remove that section.
