### ISSUE TITLE
Google Authenticator tokens not working (sometimes...)

### ISSUE THREAD

**Issue by dylansturg** [Bouke/django-two-factor-auth#95]
I'm having trouble using Google Authenticator tokens.  I have a couple local development versions of the server (Django's built in and a couple QA servers nearly identical to my prod environment).  On every setup other than my prod server (an AWS Ubuntu instance), Google tokens work fine.  On that particular server, Google tokens are always rejected as invalid ("Entered token is not valid").  I have another Ubuntu (non-AWS) server running the exact same code, same server configuration files, etc. and it works fine.

I really don't know anything about how this token generator works.  I did some digging into this code (and the django_otp code), but I can't see anything glaring that would cause this problem.

Does anyone have any idea what would cause the Google Authenticator tokens to be rejected in this context?  Or perhaps where I should be looking or variables I should tweak?  My first reaction is that it's a configuration error with my server, but I'm not sure what I would've screwed up that could cause this error.

Thanks for any help or information!

**Comment by dylansturg** [comment]
Wow, do I ever feel dumb.  I have spent more than a few hours trying to figure out what was going on here...

So it looks like my server's time was out of sync.  I kind of assumed that Ubuntu probably did some sort of fancy time syncing auto-magically.  A simple:

ntpdate -s time.nist.gov

and I was on my way with everything working as expected.

I apologize for creating an issue when the solution was right in front of me.  I'm going to go ahead and close this one.

**Comment by Bouke** [comment]
I was also thinking of a clock synchronisation issue as well. I'm glad you found the solution as well!

**Comment by ikresoft** [comment]
I am having a problem this morning all my users cant use token every time message is invalid token, I truncate table and start process again but in new process of new token error message is the same. What is going on I dont know.

**Comment by Bouke** [comment]
Have you looked into the solution listed in this question; thus checking if the local server's time is synced with UTC?
