### ISSUE TITLE
Blocking accounts after certain number of failed attempts

### ISSUE THREAD

**Issue by vilda** [Bouke/django-two-factor-auth#98]
There is no limit on the number of failed attempts. When the main password is compromised then the accounts' security relay on 2FA code strength. Which is not much given its limited size. RFC 4226 recommends to implement some scheme against bruteforce attacks.

In this case a certain configurable limit to block the account suffices.

**Comment by Bouke** [comment]
The recommendation is the following:

> 7.3.  Throttling at the Server

>   Truncating the HMAC-SHA-1 value to a shorter value makes a brute
   force attack possible.  Therefore, the authentication server needs to
   detect and stop brute force attacks.

>   We RECOMMEND setting a throttling parameter T, which defines the
   maximum number of possible attempts for One-Time Password validation.
   The validation server manages individual counters per HOTP device in
   order to take note of any failed attempt.  We RECOMMEND T not to be
   too large, particularly if the resynchronization method used on the
   server is window-based, and the window size is large.  T SHOULD be
   set as low as possible, while still ensuring that usability is not
   significantly impacted.

>    Another option would be to implement a delay scheme to avoid a brute
   force attack.  After each failed attempt A, the authentication server
   would wait for an increased T*A number of seconds, e.g., say T = 5,
   then after 1 attempt, the server waits for 5 seconds, at the second
   failed attempt, it waits for 5*2 = 10 seconds, etc.

>   The delay or lockout schemes MUST be across login sessions to prevent
   attacks based on multiple parallel guessing techniques.

**Comment by MichaelAnckaert** [comment]
I started working on this issue and so far have gotten basic functionality to work where after a number of unsuccessful tries a users account is disabled. 

Currently I have a setting called **OTP_MAX_TRIES** that can be None or a number of tries. Only when the number of maximum tries is set the extra check is activated. 

The number of tries currently caries over across devices since it's stored in the session variable. This obviously needs more finetuning. 

For those interested: https://github.com/MichaelAnckaert/django-two-factor-auth/tree/issue-98

**Comment by MarkusH** [comment]
@MichaelAnckaert unfortunately your approach is flawed. You're storing the counter in the current session which is dependent on a cookie an attacker can remove. Essentially, an attacker only needs to make sure they are not sending a cookie when requesting the login view.

I think that's something to be implemented by django_otp as a general solution to the problem.

**Comment by pckapps** [comment]
Perhaps Django Axes (https://github.com/jazzband/django-axes)  can be used as a base for this? Can treat an incorrect otp as a failed log in attempt. Anybody tried this?

**Comment by Priyanka12345678910** [comment]
Does anyone has any update on this. I ave same requirement as "Blocking accounts after certain number of failed attempts". Can anyone let me know if he has integrated django-axes with OTP page. django-axes works well with username/password page but doesn't work well with OTP page. If some as made that work please share.

**Comment by moggers87** [comment]
This has been done upstream in django-otp. There are a few things that still need to be added to make it a smoother experience for users: #299 #366
