### ISSUE TITLE
Chrome prefetch causing the TOTP qrcode to 404

### ISSUE THREAD

**Issue by kramimus** [Bouke/django-two-factor-auth#99]
In some cases, Chrome fetches /account/two_factor/qrcode/ twice, presumably due to prefetch behavior. 

The second get returns a 404 since django_two_factor-qr_secret_key gets deleted from the session on the first get. The QR code does not get rendered when this happens.

Seen on Chrome 43.

**Comment by kramimus** [comment]
Is there a reason the key delete cannot move to SetupView.done? Seems like that would be the easy fix unless this breaks some assumption about security.

**Comment by Bouke** [comment]
See #30 and d113b80c220bcf62b25d252d5980f02420c8c270 for more details on the implementation. I guess the secret could remain in the session, however I think it would be best to encrypt the secret for increased security.
